name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'
      
# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:
      
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: /dist
          build_command: npm run build-storybook
