name: Build and Publish storybook to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs Yarn
      - name: NPM Install
        run: npm install

      # Runs Build
      - name: NPM Execute build and creates tsdx files
        run: npm run build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      pages: write
      contents: read
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          token: ${{ secrets.PACKAGE_TOKEN }}
          path: /home/runner/work/govuk-frontend-react/govuk-frontend-react/storybook-static
          build_command: npm run build-storybook
