name: Build and Publish storybook to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          token: ${{ secrets.PACKAGE_TOKEN }}
          path: /home/runner/work/govuk-frontend-react/govuk-frontend-react/storybook-static
          build_command: npm run build-storybook
